// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalTradingJournal.Infrastructure.Persistence;

#nullable disable

namespace PersonalTradingJournal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JournalDbContext))]
    [Migration("20261008195353_AddCoachingAnalysisSnapshots")]
    partial class AddCoachingAnalysisSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.CoachingAnalysisRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceContractVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PacketId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseContractVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScopeKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReviewDate", "ScopeKind", "AccountId", "GeneratedAtUtc", "Id");

                    b.ToTable("CoachingAnalyses", null, t =>
                        {
                            t.HasCheckConstraint("CK_CoachingAnalyses_Scope", "(ScopeKind = 0 AND AccountId IS NULL) OR (ScopeKind = 1 AND AccountId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.DailyJournalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NeedsImprovement")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("NextTradingDay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TradingAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WentWell")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("TradingAccountId");

                    b.HasIndex("TradingDate")
                        .IsUnique()
                        .HasFilter("\"TradingAccountId\" IS NULL");

                    b.HasIndex("TradingDate", "TradingAccountId")
                        .IsUnique()
                        .HasFilter("\"TradingAccountId\" IS NOT NULL");

                    b.ToTable("DailyJournals", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyJournals_Revision", "\"Revision\" >= 1");
                        });
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.DailyJournalRevisionRecord", b =>
                {
                    b.Property<Guid>("JournalId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NeedsImprovement")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("NextTradingDay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("SavedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("WentWell")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("JournalId", "Revision");

                    b.ToTable("DailyJournalRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyJournalRevisions_Revision", "\"Revision\" >= 1");
                        });
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.InstrumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetClass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TickValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Instruments", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TopstepImportedRowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DerivedEntryExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DerivedExitExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EconomicFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Representation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("SourceRowJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradingAccountIdAtImport")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradeId")
                        .IsUnique();

                    b.HasIndex("TradingAccountIdAtImport", "SourceId")
                        .IsUnique();

                    b.ToTable("TopstepImportedRows", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeBrowseRecord", b =>
                {
                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("AverageEntryPriceSortKey")
                        .IsRequired()
                        .HasMaxLength(58)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<decimal?>("AverageExitPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GrossPnL")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetPnL")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetPnLSortKey")
                        .HasMaxLength(58)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<decimal>("OpenQuantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenQuantitySortKey")
                        .IsRequired()
                        .HasMaxLength(58)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalCosts")
                        .HasColumnType("TEXT");

                    b.HasKey("TradeId");

                    b.HasIndex("AverageEntryPriceSortKey");

                    b.HasIndex("NetPnLSortKey");

                    b.HasIndex("OpenQuantitySortKey");

                    b.HasIndex("OpenedAtUtc");

                    b.ToTable("TradeBrowse", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerSymbol")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Commission")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalExecutionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Fees")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradeId", "Sequence")
                        .IsUnique();

                    b.ToTable("TradeExecutions", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeMistakeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradingMistakeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradingMistakeId");

                    b.HasIndex("TradeId", "TradingMistakeId")
                        .IsUnique();

                    b.ToTable("TradeMistakes", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PricingCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricingPointValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TradingSetupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("TradingAccountId");

                    b.HasIndex("TradingSetupId");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeScreenshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeScreenshots", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradingAccountRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StartingBalance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TradingAccounts", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradingMistakeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TradingMistakes", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradingSetupRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TradingSetups", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradovateImportedExecutionRecord", b =>
                {
                    b.Property<Guid>("TradeExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AllocatedQuantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("AllocationIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalExecutionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SourceFillExecutedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SourceFillPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SourceFillQuantity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradingAccountIdAtImport")
                        .HasColumnType("TEXT");

                    b.HasKey("TradeExecutionId");

                    b.HasIndex("TradeId");

                    b.HasIndex("TradingAccountIdAtImport", "BrokerSymbol", "Side", "ExternalExecutionId", "AllocationIndex")
                        .IsUnique();

                    b.ToTable("TradovateImportedExecutions", (string)null);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.DailyJournalRecord", b =>
                {
                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.TradingAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.DailyJournalRevisionRecord", b =>
                {
                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.DailyJournalRecord", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TopstepImportedRowRecord", b =>
                {
                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeRecord", null)
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeBrowseRecord", b =>
                {
                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeRecord", null)
                        .WithOne()
                        .HasForeignKey("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeBrowseRecord", "TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeExecutionRecord", b =>
                {
                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeRecord", null)
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeMistakeRecord", b =>
                {
                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeRecord", null)
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.TradingMistakeRecord", null)
                        .WithMany()
                        .HasForeignKey("TradingMistakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeRecord", b =>
                {
                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.InstrumentRecord", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.TradingAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.TradingSetupRecord", null)
                        .WithMany()
                        .HasForeignKey("TradingSetupId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeScreenshotRecord", b =>
                {
                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeRecord", null)
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalTradingJournal.Infrastructure.Persistence.Records.TradovateImportedExecutionRecord", b =>
                {
                    b.HasOne("PersonalTradingJournal.Infrastructure.Persistence.Records.TradeRecord", null)
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
