<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PersonalTradingJournal.Application\PersonalTradingJournal.Application.csproj" />
    <ProjectReference Include="..\PersonalTradingJournal.Infrastructure\PersonalTradingJournal.Infrastructure.csproj" />
    <ProjectReference Include="..\PersonalTradingJournal.Contracts\PersonalTradingJournal.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
